### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by udayakumarvdm** [harukasan/go-libwebp#21]
Hi All,

When I used to import the C in go-lang, I will get the given below error. Can any one help me to clear it.

`# notification/webp
../../webp/decode.go:5:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^`

**Example code:**

> package webp
> 
> /*
> #include <stdlib.h>
> #include <webp/decode.h>
> 
> static VP8StatusCode CheckDecBuffer(const WebPDecBuffer* const buffer);
> 
> */
> import "C"
> 
> import (
> 	"fmt"
> 	"image"
> 	"unsafe"
> )

**Comment by harukasan** [comment]
The error shows that the header files are missing or unresolved.
